version: '3.8'

services:
  db:
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: cap
    ports:
      - 5432:5432